/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CouncilsIndexRouteImport } from './routes/councils/index'
import { Route as CouncilsIdRouteImport } from './routes/councils/$id'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentToolsConfigRouteImport } from './routes/agent/tools-config'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentDefinitionsRouteImport } from './routes/agent/definitions'
import { Route as AgentConfigRouteImport } from './routes/agent/config'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilsIndexRoute = CouncilsIndexRouteImport.update({
  id: '/councils/',
  path: '/councils/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilsIdRoute = CouncilsIdRouteImport.update({
  id: '/councils/$id',
  path: '/councils/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentToolsConfigRoute = AgentToolsConfigRouteImport.update({
  id: '/tools-config',
  path: '/tools-config',
  getParentRoute: () => AgentRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentDefinitionsRoute = AgentDefinitionsRouteImport.update({
  id: '/definitions',
  path: '/definitions',
  getParentRoute: () => AgentRoute,
} as any)
const AgentConfigRoute = AgentConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/system': typeof SystemRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/definitions': typeof AgentDefinitionsRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/tools-config': typeof AgentToolsConfigRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/councils/$id': typeof CouncilsIdRoute
  '/councils/': typeof CouncilsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/system': typeof SystemRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/definitions': typeof AgentDefinitionsRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/tools-config': typeof AgentToolsConfigRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/councils/$id': typeof CouncilsIdRoute
  '/councils': typeof CouncilsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/system': typeof SystemRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/definitions': typeof AgentDefinitionsRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/tools-config': typeof AgentToolsConfigRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/councils/$id': typeof CouncilsIdRoute
  '/councils/': typeof CouncilsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/system'
    | '/agent/config'
    | '/agent/definitions'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/tools-config'
    | '/channels/$name'
    | '/config/raw'
    | '/councils/$id'
    | '/councils/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/system'
    | '/agent/config'
    | '/agent/definitions'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/tools-config'
    | '/channels/$name'
    | '/config/raw'
    | '/councils/$id'
    | '/councils'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/system'
    | '/agent/config'
    | '/agent/definitions'
    | '/agent/skills'
    | '/agent/tools'
    | '/agent/tools-config'
    | '/channels/$name'
    | '/config/raw'
    | '/councils/$id'
    | '/councils/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  SystemRoute: typeof SystemRoute
  CouncilsIdRoute: typeof CouncilsIdRoute
  CouncilsIndexRoute: typeof CouncilsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/councils/': {
      id: '/councils/'
      path: '/councils'
      fullPath: '/councils/'
      preLoaderRoute: typeof CouncilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/councils/$id': {
      id: '/councils/$id'
      path: '/councils/$id'
      fullPath: '/councils/$id'
      preLoaderRoute: typeof CouncilsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/tools-config': {
      id: '/agent/tools-config'
      path: '/tools-config'
      fullPath: '/agent/tools-config'
      preLoaderRoute: typeof AgentToolsConfigRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/definitions': {
      id: '/agent/definitions'
      path: '/definitions'
      fullPath: '/agent/definitions'
      preLoaderRoute: typeof AgentDefinitionsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/config': {
      id: '/agent/config'
      path: '/config'
      fullPath: '/agent/config'
      preLoaderRoute: typeof AgentConfigRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentConfigRoute: typeof AgentConfigRoute
  AgentDefinitionsRoute: typeof AgentDefinitionsRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
  AgentToolsConfigRoute: typeof AgentToolsConfigRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentConfigRoute: AgentConfigRoute,
  AgentDefinitionsRoute: AgentDefinitionsRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
  AgentToolsConfigRoute: AgentToolsConfigRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  SystemRoute: SystemRoute,
  CouncilsIdRoute: CouncilsIdRoute,
  CouncilsIndexRoute: CouncilsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
